[package]
name = "thalo"
version = "0.1.0"
authors = ["Ari Seyhun <ariseyhun@live.com.au>"]
edition = "2021"
description = "An event sourcing & CQRS framework for Event Driven Architechture"
repository = "https://github.com/awto-rs/thalo"
license = "MIT OR Apache-2.0"
keywords = ["event-sourcing", "cqrs", "event-driven", "actors", "macros"]

[dependencies]
actix = "0.12"
async-trait = "0.1"
bb8-postgres = { version = "0.7", features = [
  "with-chrono-0_4",
  "with-serde_json-1",
] }
chrono = "0.4"
futures = "0.3"
lru = "0.7"
outbox-relay = { version = "0.1.0", path = "../outbox-relay", optional = true }
rdkafka = "0.27"
sea-query = { git = "https://github.com/SeaQL/sea-query.git", rev = "db6dc7e86a73f811275c563dd88077b8cfe6b98e", features = [
  "backend-postgres",
  "postgres",
  "postgres-json",
  "thread-safe",
] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thalo-macros = { version = "0.1.0", path = "../thalo-macros" }
thiserror = "1.0"
tokio = { version = "1.14", features = ["rt", "sync"] }
tracing = "0.1"

[features]
default = []
outbox_relay = ["outbox-relay"]
